### ISSUE TITLE
[Bug]: Unable to retrive session key by using the Citric

### ISSUE THREAD

**Issue by c0d33p** [edgarrmondragon/citric#216]
### Citric Version

0.0.9

### Python Version

3.8

### LimeSurvey Version

5.2.13+220207

### Operating System

linux

### Description

I have created dummy limesurvey docker under http://127.0.0.1:8082/index.php/admin/remotecontrol
with enabled JSON-RPC

I'm unable to connect using the Citric the authentication method is authdb for user admin

Do you have an 

### Code

```python
mlewkowicz@L192:~$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    with Client(LS_URL, 'admin', 'AAAAAAAAAA') as client:
  File "/home/mlewkowicz/.local/lib/python3.8/site-packages/citric/client.py", line 64, in __init__
    self.__session = self.session_class(
  File "/home/mlewkowicz/.local/lib/python3.8/site-packages/citric/session.py", line 60, in __init__
    self.__key: Optional[str] = self.get_session_key(
  File "/home/mlewkowicz/.local/lib/python3.8/site-packages/citric/method.py", line 42, in __call__
    return self.__caller(self.__name, *params)
  File "/home/mlewkowicz/.local/lib/python3.8/site-packages/citric/session.py", line 95, in rpc
    result = self._invoke(self._session, self.url, method, *params)
  File "/home/mlewkowicz/.local/lib/python3.8/site-packages/citric/session.py", line 132, in _invoke
    res.raise_for_status()
  File "/home/mlewkowicz/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8082/index.php/admin/remotecontrol

the example file code:
mlewkowicz@L192:~$ cat test.py 
#!/bin/env python3

from citric import Client

LS_URL = "http://127.0.0.1:8082/index.php/admin/remotecontrol"

with Client(LS_URL, 'admin', 'AAAAAAAAAA') as client:
    surveys = client.list_surveys("admin")
```

### Permissions Matrix

it's the admin account

**Comment by edgarrmondragon** [comment]
Hi @c0d33p! Thanks for submitting this issue.

I am not able to reproduce the error running [martialblog/limesurvey](https://hub.docker.com/r/martialblog/limesurvey) on port 8001.

```python
# script.py
import logging

import citric

formatter = logging.Formatter("{asctime} {levelname} {message}", style="{")

handler = logging.StreamHandler()
handler.setFormatter(formatter)

logger = logging.getLogger("citric")
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

LS_URL = "http://127.0.0.1:8001/index.php/admin/remotecontrol"

print(citric.__version__)

with citric.Client(LS_URL, "iamadmin", "secret") as client:
    users = client.list_users()
    print(users[0]["users_name"])
```

```console
$ python script.py
0.0.9
2022-02-09 19:03:51,028 INFO Invoked RPC method get_session_key with ID 276601
2022-02-09 19:03:51,320 INFO Invoked RPC method list_users with ID 213430
iamadmin
2022-02-09 19:03:51,618 INFO Invoked RPC method release_session_key with ID 41522
```

---

Can you enable "Publish API on /admin/remotecontrol"

<img width="384" alt="Screen Shot 2022-02-09 at 18 58 56" src="https://user-images.githubusercontent.com/16805946/153317138-065f7eb6-5be6-4865-aae4-03f359a1d614.png">

and check the output of

```shell
curl http://127.0.0.1:8082/index.php/admin/remotecontrol
```

---

It might also be worth looking at your LimeSurvey container logs:

```console
$ docker container logs --tail 10 citric_limesurvey_1
172.24.0.1 - - [10/Feb/2022:01:01:53 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 449 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:02:35 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 791 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:02:36 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 806 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:02:36 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 449 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:02:48 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 791 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:02:48 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 806 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:02:48 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 449 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:03:50 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 791 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:03:51 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 807 "-" "citric-client"
172.24.0.1 - - [10/Feb/2022:01:03:51 +0000] "POST /index.php/admin/remotecontrol HTTP/1.1" 200 448 "-" "citric-client"
```

**Comment by c0d33p** [comment]
The issue was related to the [martialblog/limesurvey](https://hub.docker.com/r/martialblog/limesurvey)

> LIMESURVEY_DEBUG=2
option.
After starting new docker-compose without above line in docker-compose.yml everything runs fine.

Thank you and sorry for trouble...

**Comment by edgarrmondragon** [comment]
@c0d33p thank you for sharing your findings and again for logging the issue in the first place!

I'm glad you were able to solve this by changing a container variable 😄
